export const ADD_TO_CART = "ADD_TO_CART";
export const GET_CART_LOCAL_STORAGE = "GET_CART_LOCAL_STORAGE";
export const INCREMENT_CART_ITEM = "INCREMENT_CART_ITEM";
export const DICREMENT_CART_ITEM = "DICREMENT_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const GET_CART_COUNTER_LOCAL_STORAGE = "GET_CART_COUNTER_LOCAL_STORAGE";
export const CLEAN_PRODUCTS_TO_BUY = "CLEAN_PRODUCTS_TO_BUY";
